"""Encryption at rest for the few secrets the coordinator must be able to replay —
today just the root password of an SSH-managed Linux device, kept only when the operator
ticks "remember".

Keyed by SIM_SECRET_KEY from /etc/sim-config.env (chmod 600, systemd EnvironmentFile),
generated by deploy/pi-setup.sh. Deliberately NOT derived from SIM_AGENT_TOKEN: that token
is shared with every agent and printed to the console during setup, and rotating it must
not render stored passwords unreadable.

If SIM_SECRET_KEY is unset, available() is False and callers must refuse to store a
secret rather than fall back to a weaker key.
"""
import base64
import hashlib
from . import config

_FERNET = None
_TRIED = False


def _fernet():
    """Lazily build the Fernet instance. Returns None when no usable key is configured
    or the `cryptography` package is missing."""
    global _FERNET, _TRIED
    if _TRIED:
        return _FERNET
    _TRIED = True
    raw = (config.SECRET_KEY or "").strip()
    if not raw:
        return None
    try:
        from cryptography.fernet import Fernet
    except ImportError:
        return None
    # Accept either a ready-made 32-byte urlsafe-base64 Fernet key (what pi-setup.sh
    # writes) or any other string, which we hash to the right length. Hashing keeps a
    # hand-edited env file working instead of failing at the first encrypt().
    try:
        if len(base64.urlsafe_b64decode(raw.encode())) == 32:
            key = raw.encode()
        else:
            raise ValueError
    except Exception:
        key = base64.urlsafe_b64encode(hashlib.sha256(raw.encode()).digest())
    try:
        _FERNET = Fernet(key)
    except Exception:
        _FERNET = None
    return _FERNET


def available() -> bool:
    """True if secrets can be stored. Surfaced to the dashboard via /config so the
    'remember password' checkbox can be disabled with an explanation."""
    return _fernet() is not None


def encrypt(plaintext: str) -> str:
    f = _fernet()
    if f is None:
        raise RuntimeError(
            "SIM_SECRET_KEY is not configured - cannot store a password. "
            "Add it to /etc/sim-config.env and restart sim-coordinator."
        )
    return f.encrypt(plaintext.encode()).decode()


def decrypt(token: str) -> str:
    f = _fernet()
    if f is None:
        raise RuntimeError("SIM_SECRET_KEY is not configured - cannot read stored secrets.")
    return f.decrypt(token.encode()).decode()
